//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace scm.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class resOrderDtl
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public resOrderDtl()
        {
            this.scInvOutDtls = new HashSet<scInvOutDtl>();
        }
    
        public int Id { get; set; }
        public int resOrderHdrId { get; set; }
        public Nullable<int> resMenuId { get; set; }
        public Nullable<int> resItemId { get; set; }
        public int Qty { get; set; }
        public decimal UnitPrice { get; set; }
    
        public virtual resOrderHdr resOrderHdr { get; set; }
        public virtual resMenu resMenu { get; set; }
        public virtual resItem resItem { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<scInvOutDtl> scInvOutDtls { get; set; }
    }
}
