//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace scm.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class resOrderHdr
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public resOrderHdr()
        {
            this.resOrderDtls = new HashSet<resOrderDtl>();
        }
    
        public int Id { get; set; }
        public int resCustomerId { get; set; }
        public System.DateTime dtOrder { get; set; }
        public string dtDelivery { get; set; }
        public string Remarks { get; set; }
    
        public virtual resCustomer resCustomer { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<resOrderDtl> resOrderDtls { get; set; }
    }
}
