//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace scm.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class resPreparation
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public resPreparation()
        {
            this.resPreparationDtls = new HashSet<resPrepMaterial>();
        }
    
        public int Id { get; set; }
        public string dtPrepared { get; set; }
        public int resRecipeId { get; set; }
        public decimal resQty { get; set; }
        public decimal itemty { get; set; }
        public int scItemId { get; set; }
        public int scStoreBinId { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<resPrepMaterial> resPreparationDtls { get; set; }
        public virtual resRecipe resRecipe { get; set; }
        public virtual scItem scItem { get; set; }
        public virtual scStoreBin scStoreBin { get; set; }
    }
}
