//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace scm.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class scItemSupplier
    {
        public int Id { get; set; }
        public int scItemId { get; set; }
        public int scSupplierId { get; set; }
        public int Leadtime { get; set; }
        public decimal UnitPrice { get; set; }
        public int scUomId { get; set; }
    
        public virtual scItem scItem { get; set; }
        public virtual scSupplier scSupplier { get; set; }
        public virtual scUom scUom { get; set; }
    }
}
