//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace scm.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class ScmDBContainer : DbContext
    {
        public ScmDBContainer()
            : base("name=ScmDBContainer")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<scSupplier> scSuppliers { get; set; }
        public virtual DbSet<scItem> scItems { get; set; }
        public virtual DbSet<scUom> scUoms { get; set; }
        public virtual DbSet<scType> scTypes { get; set; }
        public virtual DbSet<scStorage> scStorages { get; set; }
        public virtual DbSet<scStoreBin> scStoreBins { get; set; }
        public virtual DbSet<scItemSupplier> scItemSuppliers { get; set; }
        public virtual DbSet<scRcvHdr> scRcvHdrs { get; set; }
        public virtual DbSet<scRcvDtl> scRcvDtls { get; set; }
        public virtual DbSet<scPoHdr> scPoHdrs { get; set; }
        public virtual DbSet<scPoDtl> scPoDtls { get; set; }
        public virtual DbSet<resMenu> resMenus { get; set; }
        public virtual DbSet<resRecipe> resRecipes { get; set; }
        public virtual DbSet<resIngredient> resIngredients1 { get; set; }
        public virtual DbSet<resMenuItem> resMenuItems1 { get; set; }
        public virtual DbSet<resOrderHdr> resOrderHdrs { get; set; }
        public virtual DbSet<resCustomer> resCustomers { get; set; }
        public virtual DbSet<resOrderDtl> resOrderDtls { get; set; }
        public virtual DbSet<resCategory> resCategories { get; set; }
        public virtual DbSet<resMenuCategory> resMenuCategories { get; set; }
        public virtual DbSet<resItem> resItems { get; set; }
        public virtual DbSet<scInvOutHdr> scInvOutHdrs { get; set; }
        public virtual DbSet<scInvOutDtl> scInvOutDtls { get; set; }
        public virtual DbSet<resPreparation> resPreparations { get; set; }
        public virtual DbSet<resPrepMaterial> resPrepMaterials { get; set; }
    }
}
