//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace scm.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class scRcvDtl
    {
        public int Id { get; set; }
        public int scRcvHdrId { get; set; }
        public int scItemId { get; set; }
        public decimal Qty { get; set; }
        public int scStoreBinId { get; set; }
        public int scPoDtlId { get; set; }
    
        public virtual scRcvHdr scRcvHdr { get; set; }
        public virtual scItem scItem { get; set; }
        public virtual scStoreBin scStoreBin { get; set; }
        public virtual scPoDtl scPoDtl { get; set; }
    }
}
