//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace scm.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class scStoreBin
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public scStoreBin()
        {
            this.scRcvDtls = new HashSet<scRcvDtl>();
            this.scInvOutDtls = new HashSet<scInvOutDtl>();
            this.resPreparationDtls = new HashSet<resPrepMaterial>();
            this.resPreparations = new HashSet<resPreparation>();
        }
    
        public int Id { get; set; }
        public int scStorageId { get; set; }
        public string Code { get; set; }
        public decimal PostedQty { get; set; }
        public System.DateTime PostedDate { get; set; }
        public System.DateTime ExpiryDate { get; set; }
        public int scItemId { get; set; }
        public string BinStatus { get; set; }
    
        public virtual scStorage scStorage { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<scRcvDtl> scRcvDtls { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<scInvOutDtl> scInvOutDtls { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<resPrepMaterial> resPreparationDtls { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<resPreparation> resPreparations { get; set; }
        public virtual scItem scItem { get; set; }
    }
}
